version: "3.8"

services:
  web:
    build:
      context: .
    command: sh ./entry.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery-worker
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange_db
    ports:
      - "5432:5432"

  redis:
    image: redis

  celery-worker:
    build:
      context: .
    command: celery -A app.jobs.update_job.celery_app worker -B --loglevel=info
    depends_on:
      - db
    environment:
      - BROKER_URL=redis://redis
      - RESULT_BACKEND=redis://redis
