"""Init migration

Revision ID: 3fa2279fc7a8
Revises: 
Create Date: 2023-12-03 02:14:22.568368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa2279fc7a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('currency_name', sa.String(
                        length=30), nullable=True),
                    sa.Column('currency_symbol', sa.String(
                        length=3), nullable=True),
                    sa.Column('currency_price', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
